name:                libsme
version:             0.1.0.0
github:              "truls/libsme"
license:             LGPL-3
author:              "Truls Asheim"
maintainer:          "truls@asheim.dk"
copyright:           "Truls Asheim 2018"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Library for working and generating code for SMEIL (SME Intermediate Language)
category:            Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/truls/libsme#readme>

ghc-options:
  - -Wall
  - -Wcompat
  - -Wnoncanonical-monad-instances
  - -Wnoncanonical-monadfail-instances
  - -Wredundant-constraints
  - -Wincomplete-uni-patterns
  #- -Wincomplete-record-updates
  #- -O0
  #- -O2

cc-options:
  - -g
  - -Wall
  - -pedantic

include-dirs: cbits
c-sources: cbits/api.c

dependencies:
  - base >= 4.7 && < 5
  - text >= 1.2.2.2
  - pretty-show >= 1.6.13
  - directory >= 1.3.0.2
  - optparse-applicative >= 0.14.2.0

library:
  source-dirs: src
  dependencies:
  - language-vhdl-quote
  - containers >= 0.5.10.2
  - unordered-containers >= 0.2.8.0
  - filepath >= 1.4.1.2
  - mtl >= 2.2.1
  - uniplate >= 1.6.12
  - megaparsec >= 6.3.0
  - bimap >= 0.3.3
  - mainland-pretty >= 0.7
  - srcloc >= 0.5.1.2
  - exceptions >= 0.8.3
  - hashable >= 1.2.6.1
  - extra >= 1.6.3
  - mono-traversable >= 1.0.8.1
  - template-haskell >= 2.12.0.0
  - makefile >= 1.1.0.0
  - fgl >= 5.6.0.0
  - async >= 2.2.1
  - stm
  - integer-gmp >= 1.0.1.0
  - vector >= 0.12.0.1
  - interpolate >= 0.2.0
  - bytestring >= 0.10.8.1
  - bitwise >= 1.0.0.1
  # - file-embed >= 0.0.10.1b
  #- aeson >= 1.2.3.0
  # - split >= 0.2.3.2
  # - aeson-pretty >= 0.8.5
  #- lens >= 4.15.4
  #- recursion-schemes

  # ghc-options:
  #   - -Wall

executables:
  smec:
    main:                smec.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    # - -Wall
    dependencies:
      - libsme

  smeast:
    main:                smeast.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    # - -Wall
    dependencies:
      - libsme
      - optparse-applicative

# tests:
#   libsme-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#       - -threaded
#       - -rtsopts
#       - -with-rtsopts=-N
#     dependencies:
#       - libsme
