name:                libsme
version:             0.1.0.0
github:              "truls/libsme"
license:             LGPL-3
author:              "Truls Asheim"
maintainer:          "truls@asheim.dk"
copyright:           "Truls Asheim 2018"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Library for working and generating code for SMEIL (SME Intermediate Language)
category:            Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/truls/libsme#readme>

ghc-options:
  - -Wall

dependencies:
- base >= 4.7 && < 5
- language-vhdl-quote
# - language-smeil
- containers >= 0.5.10.2
- unordered-containers >= 0.2.8.0
- filepath >= 1.4.1.2
- directory >= 1.3.0.2
- mtl
- uniplate >= 1.6.12
- pretty-show
- mainland-pretty >= 0.6.1
- aeson >= 1.2.3.0
- bytestring >= 0.10.8.1
- split >= 0.2.3.2
- megaparsec >= 6.3.0
- aeson-pretty >= 0.8.5
- bimap >= 0.3.3
- srcloc >= 0.5.1.1
- exceptions >= 0.8.3
- lens >= 4.15.4

library:
  source-dirs: src
  # ghc-options:
  #   - -Wall

executables:
  smec:
    main:                smec.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # - -Wall
    dependencies:
    - libsme
    - optparse-applicative

  smeast:
    main:                smeast.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # - -Wall
    dependencies:
    - libsme
    - optparse-applicative

tests:
  libsme-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - libsme
